### ISSUE TITLE
Internal classes blocking extendability

### ISSUE THREAD

**Issue by jscti** [MFlisar/ComposePreferences#4]
Me again :)

Would it be possible to have access to some of your internal `ProvidableCompositionLocal` to increase extendability ?

For example, I want to create a custom preference like on Android system settings :  

![image](https://github.com/MFlisar/ComposePreferences/assets/1594035/82a443ea-bd5d-409a-82be-286cd6fde42e)

- left zone (text) would open a `PreferenceSubScreen`
- righ zone (IconButton) would be any PreferenceWidget (checkbox in my case)

But when trying to adapt `PreferenceSubScreen`, I got stuck due to internal restrictions :  
![image](https://github.com/MFlisar/ComposePreferences/assets/1594035/39e3463d-11c7-456b-8705-fc9534c87547)

Thanks

**Comment by jscti** [comment]
In the end I don't use PreferenceSubScreen but I created a sub screen that I handle with my app navController like any other screen. No limitation that way (appBar etc)

Feel free to close this issue if needed

**Comment by MFlisar** [comment]
In this case I'd say it would make sense to add this feature optionally to the existing `PreferenceSubScreen`. It does not make sense to expose the internal hierarchy management as it would allow to destroy the libraries functionality if used wrongly...

For now I close that, feel free to add that as a pull request if you want to.
